ln -s ../3rdparty/libxslt-1.1.28/python/.libs/libxsltmod.a
ln -s ../3rdparty/libxslt-1.1.28/libxslt/.libs/libxslt.a
ln -s ../3rdparty/libxslt-1.1.28/libexslt/.libs/libexslt.a
ln -s ../3rdparty/libxslt-1.1.28/tests/plugins/.libs/xmlsoft_org_xslt_testplugin.a
ln -s ../3rdparty/libxml2-2.9.3/.libs/testdso.a
ln -s ../3rdparty/libxml2-2.9.3/python/.libs/libxml2mod.a
ln -s ../3rdparty/libxml2-2.9.3/.libs/libxml2.a
ln -s ../3rdparty/openssl-1.0.2e/libssl.a
ln -s ../3rdparty/openssl-1.0.2e/libcrypto.a
ln -s ../3rdparty/libxslt-1.1.28/tests/plugins/.libs/xmlsoft_org_xslt_testplugin.so
ln -s ../3rdparty/libxml2-2.9.3/.libs/testdso.so
ln -s ../3rdparty/libxslt-1.1.28/libxslt/.libs/libxslt.so
ln -s ../3rdparty/libxslt-1.1.28/python/.libs/libxsltmod.so
ln -s ../3rdparty/libxml2-2.9.3/.libs/libxml2.so
ln -s ../3rdparty/libxml2-2.9.3/python/.libs/libxml2mod.so
ln -s ../3rdparty/libssh-0.7.2/build/src/threads/libssh_threads.so
ln -s ../3rdparty/libssh-0.7.2/build/src/libssh.so
ln -s ../3rdparty/libxslt-1.1.28/libexslt/.libs/libexslt.so
ln -s ../libnetconf-master/.libs/libnetconf.so.0.10.0
ln -s ../libnetconf-master/.libs/libnetconf.so.0
ln -s ../libnetconf-master/.libs/libnetconf.so
ln -s ../libnetconf-master/.libs/libnetconf.a
ln -s ../3rdparty/libxslt-1.1.28/libxslt/.libs/libxslt.so.1.1.28
ln -s ../3rdparty/libxslt-1.1.28/libxslt/.libs/libxslt.so.1
ln -s ../3rdparty/libxml2-2.9.3/.libs/libxml2.so.2.9.3
ln -s ../3rdparty/libxml2-2.9.3/.libs/libxml2.so.2
ln -s ../3rdparty/libssh-0.7.2/build/src/threads/libssh_threads.so.4.4.0
ln -s ../3rdparty/libssh-0.7.2/build/src/threads/libssh_threads.so.4
ln -s ../3rdparty/libssh-0.7.2/build/src/libssh.so.4.4.0
ln -s ../3rdparty/libssh-0.7.2/build/src/libssh.so.4
ln -s ../3rdparty/libxslt-1.1.28/libexslt/.libs/libexslt.so.0.8.17
ln -s ../3rdparty/libxslt-1.1.28/libexslt/.libs/libexslt.so.0
